if(NOT EXISTS "${HARBOR_HELPER}")
  message(FATAL_ERROR "harbor-update-helper missing from build output")
endif()
if(NOT EXISTS "${HARBOR_HARBOR}")
  message(FATAL_ERROR "harbor missing from build output")
endif()
get_filename_component(HELPER_DIR "${HARBOR_HELPER}" DIRECTORY)
get_filename_component(HARBOR_DIR "${HARBOR_HARBOR}" DIRECTORY)
if(NOT HELPER_DIR STREQUAL HARBOR_DIR)
  message(FATAL_ERROR "helper is not beside Harbor")
endif()
