//! Harbor — Tauri v2 application library.
//!
//! Wires the five official plugins (notification, autostart, sql, store,
//! window-state), installs the system tray (core in v2 — no plugin), wires
//! close-to-tray (keeps presence alive in the background), runs the local
//! SQLite migrations, and registers the `get_idle_seconds` command (OS-wide
//! idle via Windows `GetLastInputInfo`; see `idle.rs`).

mod foreground;
mod icons;
mod idle;

use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{Manager, WindowEvent};
use tauri_plugin_autostart::MacosLauncher;
use tauri_plugin_sql::{Migration, MigrationKind};

/// Local SQLite migrations for the client's message history.
/// (The relay has its own schema; this is the per-device local store.)
fn local_migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "create messages table",
            sql: "CREATE TABLE IF NOT EXISTS messages (
                id          TEXT PRIMARY KEY,
                partner_id  TEXT NOT NULL,
                text        TEXT NOT NULL,
                from_me     INTEGER NOT NULL,
                created_at  INTEGER NOT NULL,
                status      TEXT NOT NULL DEFAULT 'sending'
            );
            CREATE INDEX IF NOT EXISTS idx_messages_partner ON messages(partner_id, created_at);",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "add image attachment column",
            sql: "ALTER TABLE messages ADD COLUMN image TEXT;",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "create activity_history table",
            sql: "CREATE TABLE IF NOT EXISTS activity_history (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                partner_id  TEXT NOT NULL,
                exe         TEXT,
                event       TEXT NOT NULL,
                started_at  INTEGER NOT NULL,
                ended_at    INTEGER,
                duration_sec INTEGER
            );
            CREATE INDEX IF NOT EXISTS idx_activity_partner
                ON activity_history(partner_id, started_at DESC);",
            kind: MigrationKind::Up,
        },
        Migration {
            // Feature 4: real app icons. `exe` is the lowercased process name
            // (the activity event's key); `icon_data` a base64 data URL PNG or
            // NULL once the sender confirms a generated fallback. Keyed by exe
            // so one icon is cached + reused per process per device.
            version: 4,
            description: "create app_icons table",
            sql: "CREATE TABLE IF NOT EXISTS app_icons (
                exe         TEXT PRIMARY KEY,
                icon_data   TEXT,
                updated_at  INTEGER NOT NULL
            );",
            kind: MigrationKind::Up,
        },
    ]
}

/// Tray presence icons, embedded into the binary so no runtime file I/O is
/// needed. Generated by `server/scripts/make_icons.py` (the `_tray_disc`
/// variants). Online/away/offline map to the same colours as the in-app
/// presence dots (see `client/src/style.css`).
const TRAY_ONLINE: &[u8] = include_bytes!("../icons/tray-online.png");
const TRAY_AWAY: &[u8] = include_bytes!("../icons/tray-away.png");
const TRAY_OFFLINE: &[u8] = include_bytes!("../icons/tray-offline.png");

/// Swap the tray icon + tooltip to reflect the partner's presence. Called from
/// the frontend (ws.ts) on `presence`/`last_seen` events, independent of the
/// notification toggles — the tray is always visible, so it should always show
/// the partner's current state.
#[tauri::command]
fn set_tray_presence(app: tauri::AppHandle, state: String) -> Result<(), String> {
    let (bytes, tooltip) = match state.as_str() {
        "online" => (TRAY_ONLINE, "Harbor — parceiro online"),
        "away" => (TRAY_AWAY, "Harbor — parceiro ausente"),
        _ => (TRAY_OFFLINE, "Harbor — parceiro offline"),
    };
    let Some(tray) = app.tray_by_id("harbor-tray") else {
        return Ok(());
    };
    let img = tauri::image::Image::from_bytes(bytes).map_err(|e| e.to_string())?;
    tray.set_icon(Some(img)).map_err(|e| e.to_string())?;
    tray.set_tooltip(Some(tooltip)).map_err(|e| e.to_string())?;
    Ok(())
}

/// Open the Windows microphone privacy settings so the user can grant the app
/// mic access. Surfaced to the frontend because WebView2 can silently deny
/// `getUserMedia` for the microphone — its `PermissionRequested` event isn't
/// reliably fired for it (see MicrosoftEdge/WebView2Feedback#1462), so the
/// "Permitir microfone" click alone can't recover when the OS toggles the app
/// off. The only lever the user has then is this OS settings page. Non-Windows
/// targets are a no-op (Harbor is Windows-only today).
#[tauri::command]
fn open_microphone_settings() -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        // `start "" <url>` uses the empty quoted string as a window TITLE so the
        // protocol URI itself is treated as the thing to open (the classic Win32
        // `start` quirk). `cmd /C` exits the moment `start` returns.
        std::process::Command::new("cmd")
            .args(["/C", "start", "", "ms-settings:privacy-microphone"])
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        // window-state: restore/save the main window's size + position.
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations("sqlite:harbor.db", local_migrations())
                .build(),
        )
        // Mandatory auto-update (Fase 2). The updater plugin handles the signed
        // check / download / install; the process plugin exposes relaunch().
        // The frontend's `UpdateGate` drives the whole flow (see
        // client/src/features/update/UpdateGate.tsx) — nothing here touches the
        // E2E / pairing / socket / identity layer.
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .on_window_event(|window, event| {
            // Close-to-tray on the main window: hide instead of quitting so
            // presence stays online while the app runs in the background.
            if let WindowEvent::CloseRequested { api, .. } = event {
                if window.label() == "main" {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .setup(|app| {
            // Autostart: desktop-only, registered at runtime per the plugin docs.
            #[cfg(desktop)]
            {
                let _ = app.handle().plugin(tauri_plugin_autostart::init(
                    MacosLauncher::LaunchAgent,
                    Some(vec![]),
                ));
            }

            // System tray (core in v2). Menu: Open + Quit. Left-click shows the
            // main window. Quit terminates the process (presence goes offline).
            let open_i = MenuItem::with_id(app, "open", "Open Harbor", true, None::<&str>)?;
            let quit_i = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&open_i, &quit_i])?;
            // Start the tray at "offline" — `set_tray_presence` (frontend) flips
            // it to online/away once the partner's state is known over the WS.
            let start_icon =
                tauri::image::Image::from_bytes(TRAY_OFFLINE).map_err(|e| e.to_string())?;
            TrayIconBuilder::with_id("harbor-tray")
                .icon(start_icon)
                .tooltip("Harbor — parceiro offline")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        if let Some(w) = app.get_webview_window("main") {
                            let _ = w.unminimize();
                            let _ = w.show();
                            let _ = w.set_focus();
                        }
                    }
                })
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "open" => {
                        if let Some(w) = app.get_webview_window("main") {
                            let _ = w.show();
                            let _ = w.set_focus();
                        }
                    }
                    "quit" => app.exit(0),
                    _ => {}
                })
                .build(app)?;

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            idle::get_idle_seconds,
            set_tray_presence,
            foreground::get_foreground_app,
            foreground::is_key_pressed,
            icons::get_app_icon,
            open_microphone_settings
        ])
        .run(tauri::generate_context!())
        .expect("error while running Harbor");
}
