//! Harbor — Tauri v2 application library.
//!
//! Wires the five official plugins (notification, autostart, sql, store,
//! window-state), installs the system tray (core in v2 — no plugin), wires
//! close-to-tray (keeps presence alive in the background), runs the local
//! SQLite migrations, and registers the `get_idle_seconds` command (OS-wide
//! idle via Windows `GetLastInputInfo`; see `idle.rs`).

mod foreground;
mod icons;
mod idle;

use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{Manager, WindowEvent};
use tauri_plugin_autostart::MacosLauncher;
use tauri_plugin_sql::{Migration, MigrationKind};

/// Local SQLite migrations for the client's message history.
/// (The relay has its own schema; this is the per-device local store.)
fn local_migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "create messages table",
            sql: "CREATE TABLE IF NOT EXISTS messages (
                id          TEXT PRIMARY KEY,
                partner_id  TEXT NOT NULL,
                text        TEXT NOT NULL,
                from_me     INTEGER NOT NULL,
                created_at  INTEGER NOT NULL,
                status      TEXT NOT NULL DEFAULT 'sending'
            );
            CREATE INDEX IF NOT EXISTS idx_messages_partner ON messages(partner_id, created_at);",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "add image attachment column",
            sql: "ALTER TABLE messages ADD COLUMN image TEXT;",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "create activity_history table",
            sql: "CREATE TABLE IF NOT EXISTS activity_history (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                partner_id  TEXT NOT NULL,
                exe         TEXT,
                event       TEXT NOT NULL,
                started_at  INTEGER NOT NULL,
                ended_at    INTEGER,
                duration_sec INTEGER
            );
            CREATE INDEX IF NOT EXISTS idx_activity_partner
                ON activity_history(partner_id, started_at DESC);",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 4,
            description: "create app_icons table",
            sql: "CREATE TABLE IF NOT EXISTS app_icons (
                exe         TEXT PRIMARY KEY,
                icon_data   TEXT,
                updated_at  INTEGER NOT NULL
            );",
            kind: MigrationKind::Up,
        },
        Migration {
            // Bug 4: in-app Harbor notification history. `kind` is one of
            // message/presence/quick; `read` tracks the unread badge in the
            // Notifications tab. Written by services/notificationStore.ts.
            version: 5,
            description: "create notifications table",
            sql: "CREATE TABLE IF NOT EXISTS notifications (
                id          TEXT PRIMARY KEY,
                kind        TEXT NOT NULL,
                title       TEXT NOT NULL,
                body        TEXT NOT NULL,
                icon        TEXT,
                timestamp   INTEGER NOT NULL,
                read        INTEGER NOT NULL DEFAULT 0
            );
            CREATE INDEX IF NOT EXISTS idx_notifications_ts
                ON notifications(timestamp DESC);",
            kind: MigrationKind::Up,
        },
    ]
}


// Tray presence icons, embedded into the binary so no runtime file I/O is
// needed. Generated by `server/scripts/make_icons.py` (the `_tray_disc`
// variants). Online/away/offline map to the same colours as the in-app
// presence dots (see `client/src/style.css`).
const TRAY_ONLINE: &[u8] = include_bytes!("../icons/tray-online.png");
const TRAY_AWAY: &[u8] = include_bytes!("../icons/tray-away.png");
const TRAY_OFFLINE: &[u8] = include_bytes!("../icons/tray-offline.png");

/// Swap the tray icon + tooltip to reflect the partner's presence. Called from
/// the frontend (ws.ts) on `presence`/`last_seen` events, independent of the
/// notification toggles — the tray is always visible, so it should always show
/// the partner's current state.
#[tauri::command]
fn set_tray_presence(app: tauri::AppHandle, state: String) -> Result<(), String> {
    let icon_bytes = match state.as_str() {
        "online" => TRAY_ONLINE,
        "away" => TRAY_AWAY,
        "offline" => TRAY_OFFLINE,
        _ => TRAY_OFFLINE,
    };

    let icon = tauri::image::Image::from_bytes(icon_bytes).map_err(|e| e.to_string())?;

    // Update tray icon
    if let Some(tray) = app.tray_by_id("harbor-tray") {
        tray.set_icon(Some(icon)).map_err(|e| e.to_string())?;
        let tooltip = match state.as_str() {
            "online" => "Harbor — parceiro online",
            "away" => "Harbor — parceiro ausente",
            "offline" => "Harbor — parceiro offline",
            _ => "Harbor — parceiro offline",
        };
        tray.set_tooltip(Some(tooltip)).map_err(|e| e.to_string())?;
    }

    Ok(())
}

/// Open the Windows microphone privacy settings so the user can grant the app
/// mic access. Surfaced to the frontend because WebView2 can silently deny
/// `getUserMedia` for the microphone — its `PermissionRequested` event isn't
/// reliably fired for it (see MicrosoftEdge/WebView2Feedback#1462), so the
/// "Permitir microfone" click alone can't recover when the OS toggles the app
/// off. The only lever the user has then is this OS settings page. Non-Windows
/// targets are a no-op (Harbor is Windows-only today).
#[tauri::command]
fn open_microphone_settings() -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        // `start "" <url>` uses the empty quoted string as a window TITLE so the
        // protocol URI itself is treated as the thing to open (the classic Win32
        // `start` quirk). `cmd /C` exits the moment `start` returns.
        std::process::Command::new("cmd")
            .args(["/C", "start", "", "ms-settings:privacy-microphone"])
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        // window-state: restore/save the main window's size + position, but NOT
        // visibility. The app uses close-to-tray (below): `CloseRequested` calls
        // `prevent_close()` + `window.hide()` so presence stays alive in the
        // background. If the plugin also persisted `visible`, that hide would be
        // saved as `visible: false`, and the NEXT launch's `restore_state` would
        // *honour* it and skip `show()` — so Harbor would open to a blank screen
        // (the webview loads but the window never appears). Excluding VISIBLE
        // (the default is `StateFlags::all()`) breaks that loop: it saves
        // size/position/maximized/decorations only, and always calls `show()`.
        // This bit autostart (which now defaults ON) hardest: boot → hidden
        // window → "tela sem nada". See `.window-state.json` `visible: false`.
        .plugin(
            tauri_plugin_window_state::Builder::new()
                .with_state_flags(
                    tauri_plugin_window_state::StateFlags::SIZE
                        | tauri_plugin_window_state::StateFlags::POSITION
                        | tauri_plugin_window_state::StateFlags::MAXIMIZED
                        | tauri_plugin_window_state::StateFlags::DECORATIONS,
                )
                .build(),
        )
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations("sqlite:harbor.db", local_migrations())
                .build(),
        )
        // Mandatory auto-update (Fase 2). The updater plugin handles the signed
        // check / download / install; the process plugin exposes relaunch().
        // The frontend's `UpdateGate` drives the whole flow (see
        // client/src/features/update/UpdateGate.tsx) — nothing here touches the
        // E2E / pairing / socket / identity layer.
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .on_window_event(|window, event| {
            // Close-to-tray on the main window: hide instead of quitting so
            // presence stays online while the app runs in the background.
            if let WindowEvent::CloseRequested { api, .. } = event {
                if window.label() == "main" {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .setup(|app| {
            // Linux (WebKitGTK): auto-grant the microphone. WebKitGTK's default
            // permission handler DENIES getUserMedia unless a handler is
            // connected — which is why the always-on call could never open the
            // mic on Linux ("O Linux está bloqueando o microfone"). We connect
            // a permission-request handler that allows audio capture, so the
            // frontend's getUserMedia resolves instead of throwing
            // NotAllowedError. The user-gesture requirement (transient
            // activation) still applies — the frontend's first-interaction
            // auto-grant covers that (see voice.ts armAutoGrant).
            #[cfg(target_os = "linux")]
            {
                use tauri::Manager as _;
                use webkit2gtk::glib::Cast as _;
                use webkit2gtk::PermissionRequestExt as _;
                use webkit2gtk::SettingsExt as _;
                use webkit2gtk::UserMediaPermissionRequestExt as _;
                use webkit2gtk::WebViewExt as _;
                if let Some(win) = app.get_webview_window("main") {
                    let _ = win.with_webview(|webview| {
                        let wv = webview.inner();
                        // WebRTC + media capture are OFF by default in WebKitGTK.
                        // Without this, `RTCPeerConnection` is undefined in the
                        // webview and the always-on call can never work on Linux
                        // ("Can't find variable: RTCPeerConnection"). Enable them
                        // here, before the page loads.
                        if let Some(settings) = wv.settings() {
                            settings.set_enable_webrtc(true);
                            settings.set_enable_media_stream(true);
                            settings.set_enable_media_capabilities(true);
                        }
                        // Auto-grant the microphone (see the comment above).
                        wv.connect_permission_request(|_wv, request| {
                            if let Some(media) =
                                request.downcast_ref::<webkit2gtk::UserMediaPermissionRequest>()
                            {
                                if media.is_for_audio_device() {
                                    media.allow();
                                    return true;
                                }
                            }
                            false
                        });
                    });
                }
            }

            // Autostart: desktop-only, registered at runtime per the plugin docs.
            // If the plugin fails to initialize here the frontend's enable()/
            // disable() calls throw Promise rejections — the Settings surface
            // surfaces that honestly (it reverts the toggle + shows an error).
            // We log the init error too so a plugin misconfig shows up in stderr
            // rather than dying silently (the old `let _ =` swallowed the Result).
            //
            // The args open an explicit main-window URL at boot so an OS-launched
            // instance (the Windows Run key) lands on the main window rather than
            // a blank/pairing-only context — matches the user's "open Harbor" intent.
            #[cfg(desktop)]
            {
                if let Err(e) = app.handle().plugin(tauri_plugin_autostart::init(
                    MacosLauncher::LaunchAgent,
                    Some(vec!["main"]),
                )) {
                    eprintln!("[harbor] autostart plugin init failed: {e}");
                }
            }

            // System tray code enabled with libappindicator
            let open_i = MenuItem::with_id(app, "open", "Open Harbor", true, None::<&str>)?;
            let quit_i = MenuItem::with_id(app, "quit", "Quit", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&open_i, &quit_i])?;
            // Start the tray at "offline" — `set_tray_presence` (frontend) flips
            // it to online/away once the partner's state is known over the WS.
            let start_icon =
                tauri::image::Image::from_bytes(TRAY_OFFLINE).map_err(|e| e.to_string())?;
            TrayIconBuilder::with_id("harbor-tray")
                .icon(start_icon)
                .tooltip("Harbor — parceiro offline")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        if let Some(w) = app.get_webview_window("main") {
                            let _ = w.unminimize();
                            let _ = w.show();
                            let _ = w.set_focus();
                        }
                    }
                })
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "open" => {
                        if let Some(w) = app.get_webview_window("main") {
                            let _ = w.show();
                            let _ = w.set_focus();
                        }
                    }
                    "quit" => {
                        app.exit(0);
                    }
                    _ => {}
                })
                .build(app)?;

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            idle::get_idle_seconds,
            set_tray_presence,
            foreground::get_foreground_app,
            foreground::is_key_pressed,
            icons::get_app_icon,
            open_microphone_settings
        ])
        .run(tauri::generate_context!())
        .expect("error while running Harbor");
}